name: Linting

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Lint
        run: |
          python -m ruff check >> $GITHUB_STEP_SUMMARY