name: Linting

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set uv & Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Lint
        run: uv run ruff check >> $GITHUB_STEP_SUMMARY